server:
  port: 8105
spring:
  datasource:
    url: jdbc:mysql:///summer
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: user-service
mybatis:
  type-aliases-package: com.summer.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8103/eureka,http://127.0.0.1:8104/eureka
    instance:
      prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
      ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找