server:
  port: 8101
spring:
  datasource:
    url: jdbc:mysql:///summer
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.summer.pojo
