server:
  port: 8103
spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
