server:
  port: 8104
spring:
  application:
    name: eureka-server
eureka:
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8103/eureka
  instance:
    lease-expiration-duration-in-seconds: 10 # 10秒即过期
    lease-renewal-interval-in-seconds: 5 # 5秒一次心跳

